export const postsConstant = {
    GETTING_POSTS: 'GETTING_POSTS',
    POSTS_SUCCESS: 'POSTS_SUCCESS',
    POSTS_FAILED: 'POSTS_FAILED',
    ADDING_NEW_POST: 'ADDING_NEW_POST',
    NEW_POST_SUCCESS: 'NEW_POST_SUCCESS',
    NEW_POST_FAILED: 'NEW_POST_FAILED',
}